name: Build image
on:
  push:
    paths:
      - 'tailscale-versions/*'
  workflow_dispatch:

jobs:
  container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHRC
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Read Tailscale version
        id: tailscale-release
        run: |
          echo ::set-output name=version::$(cat tailscale-versions/tailscale-latest.txt)
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: monolithprojects/tailscale-up:latest,${{ steps.tailscale-release.outputs.version }}
