name: Build image
on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # container-image:
  #   runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     TAILSCALE_RELEASE: [latest, stable, unstable, v1.24, v1.23, v1.22, v1.21, v1.20]

  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Get missing tags
        id: tags
        uses: s6on/mirror-docker-tags-action@v1.1
        with:
          from: tailscale/tailscale[latest,stable,v1.24]
          to: monolithprojects/tailscale-up
          allowed-platforms: linux/amd64
          updateAll: ${{ github.event_name != 'schedule' }}
    outputs:
      matrix: ${{ steps.tags.outputs.matrix }}

  outputs:
    runs-on: ubuntu-latest
    needs: setup-matrix
    if: ${{ needs.setup-matrix.outputs.matrix }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    name: ${{ matrix.base_img }}
    steps:
      - run: |
          echo ${{ matrix }}

      # - name: Kaniko build
      #   uses: aevea/action-kaniko@master
      #   with:
      #     image: monolithprojects/tailscale-up
      #     extra_args: --build-arg TAILSCALE_RELEASE=${{ matrix.TAILSCALE_RELEASE }}
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     cache: true
      #     cache_registry: monolithprojects/cache
      #     tag: ${{ matrix.TAILSCALE_RELEASE }}
