name: Build latest
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  TAILSCALE_RELEASE: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: monolithprojects/tailscale-up
          extra_args: --build-arg TAILSCALE_RELEASE=${{ env.TAILSCALE_RELEASE }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: monolithprojects/cache
          tag: ${{ env.TAILSCALE_RELEASE }}