name: Build latest
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

matrix:
  TAILSCALE_RELEASE: [latest, stable, unstable, v1.23, v1.22, v1.21, v1.20]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: monolithprojects/tailscale-up
          extra_args: --build-arg TAILSCALE_RELEASE=${{ matrix.TAILSCALE_RELEASE }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: monolithprojects/cache
          tag: ${{ matrix.TAILSCALE_RELEASE }}