name: Build image
on:
  push:
    branches:
      - main
    paths:
      - tailscale-versions/**

jobs:
  read_tailscale_version:
    runs-on: ubuntu-latest
    outputs:
        tailscale-minor: ${{ steps.tailscale-minor.outputs.csv }}
        tailscale-patch: ${{ steps.tailscale-patch.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Tailscale version
        id: tailscale-patch
        run: |
          echo ::set-output name=version::$(cat tailscale-versions/tailscale-latest.txt)
      - name: Create semantic aliases
        uses: pr-mpt/actions-semver-aliases@v1
        id: tailscale-minor
        with:
          version: ${{ steps.tailscale-patch.outputs.version }}
          prefix: v
          major: false
          minor: true
          patch: false

  image_to_ghrc:
    runs-on: ubuntu-latest
    needs: read_tailscale_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHRC
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/monolithprojects/tailscale-up:latest,ghcr.io/monolithprojects/tailscale-up:${{ needs.read_tailscale_version.outputs.tailscale-minor }},ghcr.io/monolithprojects/tailscale-up:${{ needs.read_tailscale_version.outputs.tailscale-patch }}

  image_to_dockerhub:
    runs-on: ubuntu-latest
    needs: read_tailscale_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: monolithprojects/tailscale-up:latest,monolithprojects/tailscale-up:${{ needs.read_tailscale_version.outputs.tailscale-minor }},monolithprojects/tailscale-up:${{ needs.read_tailscale_version.outputs.tailscale-patch }}
